server:
  port: 8888

bank:
  auth:
    attempt:
      max: 3

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb?createDatabaseIfNotExist=true
    username: admin
    password: 3S!amShahr
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
  bulkhead:
    instances:
      bankService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED
